services:
  web:
    image: markoshust/magento-nginx:1.18
    ports:
      - "8081:80"
    volumes:
      - ./html:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    image: markoshust/magento-php:8.2-fpm
    volumes:
      - ./html:/var/www/html
      - ./php-fpm.conf:/usr/local/etc/php-fpm.conf
    environment:
      - COMPOSER_MEMORY_LIMIT=-1

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --log-bin-trust-function-creators=1
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7.0

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.14
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

volumes:
  db_data:
